version: 2
jobs:
  build:
    docker:
      - image: regviz/node-xcb

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "yarn.lock" }}
            - v1-dependencies-

      - run: yarn install --frozen-lockfile
      - run: yarn bootstrap

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "yarn.lock" }}

      - run: yarn build
      - run: yarn format:check
      - run: yarn lint
      - run: yarn test
      - run: yarn e2e
  #     - run: yarn regression

  deploy:
    docker:
      - image: node:8.17.0
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - npm-cache-{{ checksum "yarn.lock" }}
            - npm-cache
      - run: yarn install --frozen-lockfile
      - run:
          name: Login npm
          command: |
            echo "//registry.npmjs.org/:_authToken=${NPM_AUTH_TOKEN}" > ~/.npmrc
            npm whoami
      - run:
          name: Publish
          command: |
            yarn deploy:ci

workflows:
  version: 2
  build_pipeline:
    jobs:
      - build
      - deploy:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
